name: Quarry Release

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message to echo'
        required: true

jobs:
  echo_input:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Echo input
        run: |
          echo "Input message: ${{ github.event.inputs.message }}"
